#!/bin/bash

non-null() {
  if [ -n "$1" ]; then
    return
  fi
  echo "NULL ARGUMENT" 1>&2
  exit 2
}

must-exist() {
  if [ "$1" = "folder" ]; then
    if [ -d "$2" ]; then
      return
    else
      echo "not a folder: <$2>" 1>&2
      exit 5
    fi
  fi

  if [ -e "$2" ]; then
    return
  else
    echo "file not found: <$2>" 1>&2
    exit 12
  fi
}

non-existent() {
  if [ -e "$1" ]; then
    echo "File exists: <$1>" 1>&2
    exit 4
  fi
}
    
ensure-init() {
  if [ -e ".init" ]; then
    return
  else
    echo "offdroid workspace not initialized" 1>&2
    exit 1
  fi
}

ensure-have-xml() {
  if [ -d ".offdroid-xml" ]; then
    return
  else
    echo "xml files were not found." 1>&2
    exit 2
  fi
}

ensure-sdk-set() {
     if [ -f .offdroid-sdk-folder ]; then
       return
     else
       echo "no android sdk has been set." #TODO tell them use create-barebones-sdk or set-sdk accordingly
     fi 
}

create-sources() {
  if [ -e .sources ]; then
    return
  else
    echo -n > .sources
  fi
}

usage() {
  echo -e "$1" 1>&2
  exit 1
}
 
non-null "$1"

################offdroid cd ######################
if [ "$1" = "cd" ]; then
  export OFFDROID=`pwd`
  export PATH="$PATH:$OFFDROID"
  cd "$2"

############### offdroid init ####################
elif [ "$1" = "init" ]; then
  $OFFDROID/init

############## offdroid fetch-xmls ###############
elif [ "$1" = "fetch-xmls" ]; then
  ensure-init
  shift
  $OFFDROID/fetch-xmls $@

############# offdroid list-packages #############
elif [ "$1" = "list-packages" ]; then
  node $OFFDROID/get-addons.js repo .offdroid-xml/.offdroid-urlmap .offdroid-xml/.offdroid-filemap > .all-urls
  node $OFFDROID/get-addons.js new  .offdroid-xml/.offdroid-urlmap .offdroid-xml/.offdroid-filemap > .new
  echo "LISTING FINISHED" 1>&2

########## offdroid create-barebones-sdk #########
elif [ "$1" = "create-barebones-sdk" ]; then
  FOLDER="$2"
  non-null "$FOLDER"
  non-existent "$FOLDER"
  SOURCE=""
  if [ "$3" = "from" ]; then
    SOURCE="$4"
    non-null "$SOURCE"
  else
    echo "please peovide the tools archive/director to install" 1>&2
    exit 2
  fi
  $OFFDROID/create-barebones-sdk "$SOURCE" "$FOLDER"
  $OFFDROID/offdroid set-sdk "$FOLDER"

################## offdroid set-sdk #############
elif [ "$1" = "set-sdk" ]; then
  SDK="$2"
  non-null "$SDK"
  must-exist folder "$SDK"
  must-exist file "$SDK/tools/android"
  echo -n "$SDK" > .offdroid-sdk-folder

############# offdroid select-packages ##########
elif [ "$1" = "select-packages" ]; then 
  node $OFFDROID/server.js 8080 list-only &
  ensure-sdk-set
  $OFFDROID/launch-android
  curl -s "127.0.0.1:8080/?close-server" > .selected-packages

############## offdroid create-filemap ##########
elif [ "$1" == "create-filemap" ]; then
  SOURCE="$2"
  if [ -e "$SOURCE/.offdroid-filemap" ]; then
     echo "filemap exists for <$SOURCE>"
  else
     "$OFFDROID"/create-filemap "$SOURCE"
  fi
    
############# offdroid add-source ###############
elif [ "$1" = "add-source" ]; then
  create-sources
  SOURCE="$2"
  non-null "$SOURCE"
  if grep -F "$SOURCE" < .sources; then
    echo "already in source-list <$SOURCE>" 1>&2
  else
    if [ -e "$SOURCE/.offdroid-filemap" ]; then
       echo "$SOURCE" >> .sources
       echo "SOURCE ADDED <$SOURCE>" 1>&2
    else
       echo "No filemap found in <$SOURCE>; create one? (y/n) "
       read PROMPT
       if [ "$PROMPT" = "y" ]; then
          echo "Creating filemap for <$SOURCE>; this might take several minutes, based on the folder's size" 1>&2
          $OFFDROID/create-filemap "$SOURCE"
          echo "$SOURCE" >> .sources
          echo "SOURCE ADDED <$SOURCE>" 1>&2
       else
          echo "SOURCE WAS NOT ADDED" 1>&2
          exit 1
       fi
    fi 
  fi
############# offdroid list-sources ##############
elif [ "$1" = "list-sources" ]; then
  cat .sources

############# offdroid launch-manager ############
elif [ "$1" = "launch-server" ]; then
  MISSING=".missing[--$(date)--]"
  rm -i .missing-latest
  ln -s "$MISSING" .missing-latest
  sudo node $OFFDROID/server.js 0 | tee -a "$MISSING" 
  #  $OFFDROID/launch-android      
  curl -s "127.0.0.1:8080/?close-server" > /dev/null

############# offdroid latest-tool ###############
elif [ "$1" = "latest-tool" ]; then
  if [ -e .all-urls ]; then
    $OFFDROID/latest-tool
  else
    $OFFDROID/offdroid list-packages
    $OFFDROID/latest-tool
  fi

else
  echo "Unknown command: $1" 1>&2
  exit 1
fi

