#!/bin/bash

non-null() {
  if [ -n "$1" ]; then
    return
  fi
  echo "NULL ARGUMENT" 1>&2
  exit 2
}

must-exist() {
  if [ "$1" = "folder" ]; then
    if [ -d "$2" ]; then
      return
    else
      echo "not a folder: <$2>" 1>&2
      exit 5
    fi
  fi

  if [ -e "$2" ]; then
    return
  else
    echo "file not found: <$2>" 1>&2
    exit 12
  fi
}

non-existent() {
  if [ -e "$1" ]; then
    echo "File exists: <$1>" 1>&2
    exit 4
  fi
}
    
ensure-init() {
  if [ -e ".init" ]; then
    return
  else
    echo "offdroid workspace not initialized" 1>&2
    exit 1
  fi
}

ensure-have-xml() {
  if [ -d ".offdroid-xml" ]; then
    return
  else
    echo "xml files were not found." 1>&2
    exit 2
  fi
}

ensure-sdk-set() {
     if [ -f .offdroid-sdk-folder ]; then
       return
     else
       echo "no android sdk has been set." #TODO tell them use create-barebones-sdk or set-sdk accordingly
     fi 
}

non-null "$1"

############### offdroid init ####################
if [ "$1" = "init" ]; then
  ./init

############## offdroid fetch-xmls ###############
elif [ "$1" = "fetch-xmls" ]; then
  ensure-init
  ./fetch-xmls

############# offdroid list-packages #############
elif [ "$1" = "list-packages" ]; then
  ensure-have-xml
  node get-addons.js repo .offdroid-xml/.urlmap .offdroid-xml/.filemap > .all-urls

########## offdroid create-barebones-sdk #########
elif [ "$1 = "create-barebones-sdk" ]; then
  FOLDER="$2"
  non-null "$FOLDER"
  non-existent "$FOLDER"
  SOURCE=""
  if [ "$3" = "from" ]; then
    SOURCE="$4"
    non-null "$SOURCE"
  else
    SOURCE="$(./get-latest-tool-zip)"
  fi
  ./create-barebones-sdk "$SOURCE" "$FOLDER"
  ./offdroid set-sdk "$FOLDER"

################## offdroid set-sdk #############
elif [ "$1" = "set-sdk" ]; then
  SDK="$2"
  non-null "$SDK"
  must-exist folder "$SDK"
  must-exist file "$SDK/tools/android"
  echo -n "$SDK" > .offdroid-sdk-folder

############# offdroid select-packages ##########
elif [ "$1" = "select-packages" ]; then 
  node ./server.js 8080 only-select &
  ensure-sdk-set
  ./launch-android
  curl -s "127.0.0.1:8080/?close-server" > .selected-packages

############# offdroid add-source ###############
elif [ "$1" = "add-source" ]; then
  create-sources
  SOURCE="$2"
  non-null "$SOURCE"
  if grep -F "$SOURCE" < .sources; then
    echo "already in source-list <$SOURCE>" 1>&2
  else
    echo "$SOURCE" >> .sources

############# offdroid list-sources ##############
elif [ "$1" = "list-sources" ]; then
  cat .sources

############# offdroid launch-manager ############
elif [ "$1" = "launch-manager" ]; then
  node ./server.js 8080 &
  ./launch-android      
  curl -s "127.0.0.1:8080/?close-server" > /dev/null

############# offdroid latest-tool ###############
elif [ "$1" = "latest-tool" ]; then
  if [ -e .all-urls ]; then
    ./latest-tool
  else
    node get-addon.js .offdroid-xml/.urlmap .offdroid-xml/.filemap > .all-urls
    ./latest-tool
  fi

else
  echo "Unknown command: $1" 1>&2
  exit 1
fi

